import _ from 'lodash'
import { createRandomGenerator, generateRandomSeed, RandomGenerator } from "./RandomUtils.lib";

export namespace Config {
  export const COLORS = [
    '#FFFFFF',
    '#FF0000',
    '#F0FD91',
    '#1CA3FB',
    '#C66DC6',
    '#26E980',
    '#FDA25E',
    '#34FFFD'
  ];
  export const COLORS_SIZE = COLORS.length;
  export const HOLES_SIZE = 4;
  export const TRIES_SIZE = 20;
}

export type Row = string[];
export type Board = Row[];
export type Solution = Row;

export type GameStatus = 'WON' | 'LOST' | 'ACTIVE'
export type AttemptResult = {
  rightRight: number, //right color and right position
  rightWrong: number, //right color but wrong position
  wrongWrong: number  //wrong color
}

export class MasterMindBoard {
  private readonly _board: Board;
  private readonly _solution: Solution;
  private _currentRow: number;
  private _status: GameStatus = 'ACTIVE';
  private _tries: number;

  constructor(solution: Solution, tries: number) {
    this._board = [];
    this._currentRow = 0;
    this._solution = solution;
    this._tries = tries;
  }

  public checkSolution(attempt: Row): GameStatus {
    if (this._status != 'ACTIVE') {
      return this._status;
    }

    this._board[this._currentRow] = attempt
    this._checkMove(attempt)
    return this._status;
  }

  public getAttempts(): AttemptResult[] {
    return this._board.map(row => this._checkAttempt(row))
  }

  private _checkAttempt(row: Row): AttemptResult {
    const result: AttemptResult = {
      rightRight: 0,
      rightWrong: 0,
      wrongWrong: 0
    }

    const solution: (string | undefined)[] = [...this._solution]

    for (let i = 0; i < row.length; i++) {
      if (row[i] == solution[i]) {
        solution[i] = undefined
        result.rightRight++;
      } else {
        const solutionIndex = solution.indexOf(row[i]);
        if (solutionIndex != -1) {
          solution[solutionIndex] = undefined
          result.rightWrong++;
        } else {
          result.wrongWrong++;
        }
      }
    }

    return result;
  }

  public getBoard(): Board {
    return [...this._board];
  }

  public getStatus(): GameStatus {
    return this._status;
  }

  private _checkMove(attempt: Row) {
    if (_.isEqual(this._solution, attempt)) {
      this._status = 'WON'
    } else {
      this._currentRow += 1
    }
    if (this._tries < this._currentRow) {
      this._status = 'LOST'
    }
  }
}


const createRandomSolution: (config?: { length?: number, colors?: string[] }, random?: RandomGenerator,) => Solution = (
    {
      length = Config.HOLES_SIZE,
      colors = Config.COLORS
    } = {},
    random= createRandomGenerator("default")) => {
  if (length > colors.length) {
    throw new Error(`Solution length cannot be greater than ${colors.length} size`);
  }

  console.log(`Creating random solution of length ${length} of colors [${colors}]`)
  // copy colors array
  const solution: Solution = [];
  for (let i = 0; i < colors.length; i++) {

    solution[i] = colors[i];
  }

  return random.shuffleArray(solution).slice(0, length);
}

const createBoard: (config?: {
  guesses?: number,
  size?: number,
  colors?: string[]
}, seed?: string) => MasterMindBoard = (
    {
      guesses = Config.TRIES_SIZE,
      size = Config.HOLES_SIZE,
      colors = Config.COLORS
    } = {},
    seed = generateRandomSeed()
) => {
  const random = createRandomGenerator(seed);
  const solution = createRandomSolution({length: size, colors}, random)
  return new MasterMindBoard(solution, guesses)
}


// const createGenerator: (seed: string) => RandomGenerator = (seed: string) => {
//   // method body was generated by Github Copilot, with my modifications on radix (36 vs 10) and removed const variable after parseInt
//   let current = parseInt(seed, 36)
//   return {
//     nextInt: () => {
//       current = (current * 16807) % 2147483647
//       return current
//     }
//   }
// }
//
// const loadBoard: (boardId: string) => MasterMindBoard = (boardId) => {
//   const randomGenerator = createGenerator(boardId)
//   const colors = [...Config.COLORS]
//
//   return new MasterMindBoard()
// }

export default {
  createRandomSolution,
  createBoard,

}
